### ISSUE TITLE
bug(query): consuming input failed: range start index 6432 out of range for slice of length 56

### ISSUE THREAD

**Issue by kemingy** [tensorchord/VectorChord-bm25#19]
This happens during the query through the index with an extremely **sparse** token table:

```
psycopg.OperationalError: consuming input failed: range start index 6432 out of range for slice of length 56
ERROR:  relcache reference 0x7fe1c6713bf8 is not owned by resource owner TopTransaction
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

To reproduce this error:

- use the branch: https://github.com/tensorchord/VectorChord-bm25/compare/main...kemingy:VectorChord-bm25:token_interface (need to delete everything related to tocken and other JSON include_bytes function)
- use the bm25 bench code: https://gist.github.com/kemingy/1f5ebd6788f7f107f2e37a32142612b1#file-on_pgbm25_unicode-py
- cmd: ` python -m benchmark.on_pgbm25_unicode -d fiqa --top_k 10`

**Comment by kemingy** [comment]
Details added, cc @VoVAllen

**Comment by silver-ymz** [comment]
#20 should fix it. @kemingy

**Comment by kemingy** [comment]
> #20 should fix it. @kemingy

I have confirmed that #20 fixed this.
